### ISSUE TITLE
Refactoring and cleanup

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3001]
## Overview
This issue is an epic to collect a list of proposals for code refactoring, file rearrangement or cleanups with the purpose to unify the design and strategy in organization the source code in the project.

### Restriction to type of changes
The important restriction is that changes should not impact functionality. Exceptions must be well justified.

### How to use this issue
Proposals will be collected in the description of the issue and updated when new items are added or status of existing is changed. 
From this issue multiple PR's will be spawn and linked to the issue.

### Proposals
- [ ] __Create _SourceEnclosing_ helper and remove LogSource and Metrics.Source__
  With simple macro we can eliminate creating LogSource on many places. We already have macro introduced here https://github.com/rchain/rchain/pull/1670#discussion_r227012153.
  This can be improved without the need to have implicit parameter for logger functions although with Metrics it's little more complex.
  Little complication is for shared project itself because macros must be compiled separately. One solution is to create subproject.
  https://www.scala-sbt.org/1.x/docs/Macro-Projects.html
  
- [ ] __Remove _metric_ cache, Kamon already keep internal map__
  https://github.com/rchain/rchain/blob/66b93e3/node/src/main/scala/coop/rchain/node/diagnostics/effects/package.scala#L117
  See Kamon source _MetricRegistry#lookupMetric_. Maybe _timer_ should be in bracket to ensure stop (?).

- [ ] __Replace custom `Time` with cats `Timer`__
  We can define custom [Clock](https://typelevel.org/cats-effect/datatypes/clock.html) and use cats `Timer` object. Time is introduced here https://github.com/rchain/rchain/pull/1558.
  Examples of `Timer` in tests and virtual (logical) time.
  https://blog.softwaremill.com/time-traveling-in-tests-with-cats-effect-b22084f6a89
  https://monix.io/api/3.0/monix/execution/schedulers/TestScheduler.html
    
- [ ] __Mock of Event#publish to be referentially transparent__
  https://github.com/rchain/rchain/blob/b5ba61/comm/src/test/scala/coop/rchain/p2p/EffectsTestInstances.scala#L129
  Move mock from _comm_ project (?).

- [ ] __Define _syntax_ trait for all extensions in _models_ project for easy import__
  Implicit class should extend `AnyVal` to prevent boxing.
  https://github.com/rchain/rchain/blob/003e2a8e/models/src/main/scala/coop/rchain/models/BlockHash.scala#L10-L12
  https://github.com/rchain/rchain/blob/af91c36d1/models/src/main/scala/coop/rchain/models/either/syntax/Either.scala#L9
- [x] __Remove or comment out unused code__
https://github.com/rchain/rchain/blob/f43905bd/rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala#L20-L27 e.g.
- [ ] __Move ProtoUtil methods not related to casper into to models project. Check for other model logic in other projects__
https://github.com/rchain/rchain/blob/9ef40ea099e7d3328d485144a2d7c92b2000709b/casper/src/main/scala/coop/rchain/casper/util/ProtoUtil.scala#L28
- [ ] __Cleanup all metrics: unify names, remove unused, add necessary__
- [ ] **Review the TODO comment in [Main.scala](https://github.com/rchain/rchain/blob/5d7372884/node/src/main/scala/coop/rchain/node/Main.scala#L89-L90) if it's still relevant because referenced JVM bug seems resolved.**
- [ ] **Rename the generated bnfc to `Parser` instead of `Syntax` based on the discussion** https://github.com/rchain/rchain/pull/3193#discussion_r519160300
https://github.com/rchain/rchain/blob/116c21bf647bc634251b13bd8021487663b560fb/project/BNFC.scala#L95
- [ ] **Rewrite using tailRecM** https://github.com/rchain/rchain/blob/dcd5ee6656adf572bd4963844a880d893593410a/rspace/src/main/scala/coop/rchain/rspace/SpaceMatcher.scala#L72
- [ ] **Rewrite code where `traverse` is used, make it concurrent using streams with parJoin** 
- [ ] **tailRecM?** https://github.com/rchain/rchain/blob/6dd06305020f02f9fed99c7eda6cbd980fdb0b7d/rholang/src/main/scala/coop/rchain/rholang/interpreter/Reduce.scala#L87

**Comment by zsluedem** [comment]
1. Rename the generated bnfc to `Parser` instead of `Syntax` based on the discussion 
https://github.com/rchain/rchain/blob/116c21bf647bc634251b13bd8021487663b560fb/project/BNFC.scala#L95

related discussion https://github.com/rchain/rchain/pull/3193#discussion_r519160300

**Comment by zsluedem** [comment]
We got two lmdb key value implementation. We should just have one and reused.

https://github.com/rchain/rchain/blob/0fb0c616dadb553b7b1bea09e448e7a0e1ff9765/casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala#L15-L89

https://github.com/rchain/rchain/blob/0fb0c616dadb553b7b1bea09e448e7a0e1ff9765/rspace/src/main/scala/coop/rchain/rspace/history/Store.scala#L39-L104

**Comment by tgrospic** [comment]
The idea is to remove [Store](https://github.com/rchain/rchain/blob/b38985d9/rspace/src/main/scala/coop/rchain/rspace/history/Store.scala#L16) and [LMDBStore](https://github.com/rchain/rchain/blob/b38985d9d1/shared/src/main/scala/coop/rchain/lmdb/LMDBStore.scala#L13) in favor of [KeyValueStore](https://github.com/rchain/rchain/blob/a8cb29ef/shared/src/main/scala/coop/rchain/store/KeyValueStore.scala#L5) and [LmdbKeyValueStore](https://github.com/rchain/rchain/blob/83c9509cf2/casper/src/main/scala/coop/rchain/casper/storage/LmdbKeyValueStore.scala#L15) when all code will be moved.

File based DAG storage can now be removed, and with LFS, file based block store also. This leaves only RSpace on the old Store.
