### ISSUE TITLE
REV vaults (number channel) merging

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3513]
## Overview

PoS (Proof of Stake contract) needs to collect validator rewards in PoS vault. If PoS vault is used directly in each block it will create conflict when merging blocks. In attempt to resolve this current implementation of PoS creates REV vault for each active validator (per validator vaults).
This is not enough when multiple blocks are created by the same validator in which case merging must reject the whole block because per validator vault will be conflicting.
https://github.com/rchain/rchain/blob/cb5ec1328132d92425935eeea478ffce148f94be/casper/src/main/resources/PoS.rhox#L55-L72

Another issue is slow refund operation in PoS which not only return unused REV to the deployer but also distribute rewards to validators by their stake.
https://github.com/rchain/rchain/blob/cb5ec1328132d92425935eeea478ffce148f94be/casper/src/main/resources/PoS.rhox#L295-L308

## Solution

As a first implementation merging number channels will be done for channels holding REV balances which means that PoS don't need per validator vaults and can directly work with PoS vault.

To resolve slow refund, distribution of rewards should be done only on epoch change or slashing and not together with refund operation which will speed up block processing time.

## Design

To implement merging of REV balances to major changes needs to be done.

- [x] 1. Modify the Rholang reducer to collect channel hashes which are used to hold REV balance in NonNegativeNumber contract.
    #3492
- [x] 2. Modify Rholang Runtime to persist data about mergeable channels (REV balances) on disk.
    #3492
- [x] 3. Modify conflict detection and deploy dependency calculation to skip mergeable channels as a special case.
    #3492
- [x] 4. Modify mergeable logic to support for merging values on mergeable channels, in this case Rholang `Int` types used as REV balances.
    #3492
- [x] #3514
  #3559
    - Rewards distribution should be done lazily only when is necessary and not on every block (epoch change, slashing).
    - PoS address should be replaced with multisig vault (the same as existing coop vault).
- [x] Create unforgeable name to tag number channels, now fixed __MERGEABLE__ name is used.
  #3577
- [x] Implement rejections for merged number channels which are negative or overflow.
  #3591
- [x] Add additional tests for number channel merging logic.
