### ISSUE TITLE
RadixHistory (future work)

### ISSUE THREAD

**Issue by hilltracer** [rchain/rchain#3589]
## Overview
Now we have an [implementation](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/rspace/src/main/scala/coop/rchain/rspace/history/instances/RadixHistory.scala#L30), [Unit tests](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/rspace/src/test/scala/coop/rchain/rspace/history/HistoryActionTests.scala#L19), [code for testing performance](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/node/src/test/scala/coop/rchain/node/perf/HistoryGenKeySpec.scala#L24), and [results](https://docs.google.com/presentation/d/1p8_uevkwfyibXeQ5GqSNPeVzIe5xV9GR-HuRGq2YJbY/edit?usp=sharing) of this testing. But many things could be improved.

### Documentation
- [x] #3588
- [ ] #3587

### Refactoring
- [x] #3670
- [ ] Refactoring export/import procedures
    - [ ] rewrite [rspace exporter](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/rspace/src/main/scala/coop/rchain/rspace/state/RSpaceExporter.scala#L16)
    - [ ] change export data [basic types](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/shared/src/main/scala/coop/rchain/state/TrieExporter.scala#L6)
    - [ ] Move [export procedures](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala#L196-L439) to another file
    - [ ] Add import export methods in [history trait](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/rspace/src/main/scala/coop/rchain/rspace/history/History.scala#L23)
    - [ ] Change export countable items from HistoryNodes to ColdStore records.

### Acceleration
- [ ] #3581
- [ ] Saving small data in History without ColdStore
- [ ] Import/Export acceleration (see [Parallel traversing algorithm](https://docs.google.com/presentation/d/1Ts0yDQJqcVZnPE4Q_4sKA6Ng_1hlz0TO6B-b5X7jSp0/edit?usp=sharing))

### New features
- [ ] Add a non-hashable field to the serialized data of the node, and implement a collision resolution mechanism in KVDB. For example, we can use method [open adressing](https://en.wikipedia.org/wiki/Open_addressing)
- [ ] Controlling the number of simultaneously running processes when [modifying history](https://github.com/rchain/rchain/blob/859ae7cc4523f2f6d0b33fca21ff3d0ec3462b49/rspace/src/main/scala/coop/rchain/rspace/history/RadixTree.scala#L713) (Need testing to see if this is necessary, or Monix solves the problem)

**Comment by tgrospic** [comment]
@hilltracer Why _Adding 1 byte to hold the version in each Node during serialization._ is required?

**Comment by hilltracer** [comment]
> @hilltracer Why _Adding 1 byte to hold the version in each Node during serialization._ is required?

@tgrospic Because it will allow us to make further changes to the implementation. Otherwise, we will have to recalculate hashes and hard fork every time we change the data format.

**Comment by hilltracer** [comment]
@tgrospic For example, if we want to add a field to our nodes to resolve collisions in KVDB. We could use one bit from this byte. It's just one byte for all 256 items in the node, it's a small overhead.

**Comment by tgrospic** [comment]
We were discussing about collision solution and I don't think changing node structure should be right approach.

Please add this as a suggestion for future work. It will be part of [RCHIP](https://github.com/rchain/rchip-proposals) process where specification will be added also.

We need to be clear what is really necessary for HF2 and what can be done later. E.g. improving cache is also something we will not plan for HF2.

**Comment by tgrospic** [comment]
> Remove the used algebraic data types and rewrite the implementation in the Tagless-Final style

@hilltracer Radix tree types (Node, Leaf) is not what I meant to rewrite in tagless-final style, it's the structure used in implementation like ByteVector or Array[Byte] with operations like head, tail or index access. The purpose is to abstract these operations and make the code easier to translate in other languages or check behavior with different structures.

NOTE: It seems that extra line for this item in unnumbered list creates extra space for every item in the list.
