### ISSUE TITLE
RPC release for main net launch

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3642]
## Overview

**RPC release: [v0.12.5+rpc](https://github.com/rchain/rchain/releases/tag/v0.12.5%2Brpc)**
**Docker image: [`rchain/rnode:v0.12.5__rpc`](https://hub.docker.com/layers/rnode/rchain/rnode/v0.12.5__rpc/images/sha256-88c8388413c785b6b7fd5fe9299179822c22e9cab24492c4279e2f1631b1fc60?context=explore)**

RPC main net will be launched with [v0.12.5+rpc](https://github.com/rchain/rchain/releases/tag/v0.12.5%2Brpc) release of RNode.

Some issues are discovered which requires additional changes and fixes, so for that purpose special build will be created for RPC without touching RChain's main net and compatibility with version `0.12.x`.

All changes are included in `dev` branch and duplicated in `feature/v0.12-rpc` branch for RPC release. PRs on this branch have `[RPC]` prefix in the title and labeled with `rpc-release`.

- [x] Introduce `shardId` field to deploy data to prevent relay of deploys between shards
  #3628
  #3631
  #3645
- [x] Introduce config parameters for multi-sig vault used in PoS contract
  #3625
  #3638
  #3645
- [x] Fix multi-sig vault to work with public key authentication
  #3647
  #3639 + #3643
  #3641
  #3648
  #3654 
- [x] Add lazy and/or boolean operators (for multi-sig fix)
  #3362
  #3649
  #3652
- Not required ~Fix for transaction balance script (update for `v0.12.x` release which must be updated on main net also)~
  ~#3653~

**Comment by Bill-Kunj** [comment]
@tgrospic After Monday morning this is a blocking issue for RPC. Is there an update?
