### ISSUE TITLE
Introduce support for effectful testing

### ISSUE THREAD

**Issue by tgrospic** [rchain/rchain#3719]
## Overview

Currently, we don't have support for `F[_]` effectful computation in tests so tests are using `_.runSyncUnsafe()` to get the value and assert result. This is not desired, recommended, runs slower and also more more difficult to read and write.

## Solution

Introduce libraries to extend _Scalatest_ and _scalacheck_ to support working with `F[_]` values without hacks.
https://typelevel.org/cats-effect/docs/2.x/guides/testing

Two libraries that we need are:
1. `cats-effect-testing` which enables body of tests to be effect type like IO or Task
  https://github.com/typelevel/cats-effect-testing#scalatest
1. `ScalaCheck Effect` which enables property testing with effectful values `forAllF`
  https://github.com/typelevel/scalacheck-effect#scalacheck-effect

- [x] Upgrade Scalatest, scalacheck and scalactic to latest versions to support cats-effect-testing which can only works with Scalatest 3.1.0
  https://github.com/typelevel/cats-effect-testing/blob/v0.3.0/build.sbt#L56
- [x] Introduce `monix-testing-scalatest` library to support minix Task in tests
  https://github.com/monix/monix-testing
- [ ] Introduce `cats-effect-testing` and `scalacheck-effect` into the project and improve InMemoryKeyValueStoreSpec and LmdbKeyValueStoreSpec by using effectful version. This means removal of _.runSyncUnsafe() by using `forAllF` instead of `forAll` together with using Prop instead of assert or should (e.g. `shouldBe` is the same as `?=`).
    - examples of property based tests can be found here (for now only on feature/v0.12 branch)
     https://github.com/rchain/rchain/blob/40d15bf88d343ea5eea904a6bfc82306ce696615/casper/src/test/scala/coop/rchain/casper/util/BlockHashSignatureSpec.scala#L14-L72
- [ ] Add WebApi tests as property based tests like for KeyValueStore. Generate arbitrary input and output data and assert ib underlying BlockApi received right input and returned right output.

**Comment by stanislavlyalin** [comment]
I found [only one example](https://github.com/typelevel/scalacheck-effect#scalacheck-effect) of ScalaCheck Effect usage. Is there a single source of scala libraries and documentation?
When I tried to run code from the example
```scala
it should "<test description>" in {
  val p: PropF[Task] =
    PropF.forAllF { (x: Int) =>
      Task(x).map(res => assert(res == x))
    }
  val result: Task[Test.Result] = p.check()
  result.flatMap(r => Task(println(r)))
}
```
I got compile error
```
No implicit view available from monix.eval.Task[org.scalatest.Assertion] => org.scalacheck.effect.PropF[F]
```
What did I miss?

**Comment by Adminsupportteamm** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
